loadmodule /opt/redis-stack/lib/rejson.so
loadmodule /opt/redis-stack/lib/redisearch.so

requirepass localpass
bind 0.0.0.0

maxmemory 512mb
maxmemory-policy noeviction # Never delete anything when storage got full.

appendonly no
save 900 1
save 300 10
save 60 10000

stop-writes-on-bgsave-error yes
dbfilename dump.rdb
dir /data