requirepass localpass
bind 0.0.0.0

maxmemory 512mb
# Never delete anything when storage got full.
maxmemory-policy noeviction

appendonly no
save 900 1
save 300 10
save 60 10000

stop-writes-on-bgsave-error yes
dbfilename dump.rdb
dir /data