services:
  mysql:
    container_name: local-mysql
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: localdb
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./config/local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./config/local/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volume/local/mysql/data:/var/lib/mysql

  rabbitmq:
    container_name: local-rabbitmq
    image: rabbitmq:4.2-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management Console
      - "61613:61613" # STOMP
    volumes:
      - ./config/local/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/local/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./volume/local/rabbitmq/data:/var/lib/rabbitmq

  redis:
    container_name: local-redis
    image: redis/redis-stack:7.4.0-v8
    ports:
      - "6379:6379"
      - "8001:8001" # GUI
    volumes:
      - ./volume/local/redis/data:/data
    environment:
      - REDIS_ARGS=--requirepass localpass --maxmemory 512mb --maxmemory-policy noeviction --appendonly no --save 900 1 --save 300 10 --save 60 10000 # I couldn't find the way doing this as conf file.
