spring:
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/
    
  datasource:
    url: jdbc:mysql://localhost:3306/localdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: localuser
    password: localpass
    driver-class-name: com.mysql.cj.jdbc.Driver