spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:classpath:/local/yml/application-local-mysql.yml
      - optional:classpath:/local/yml/application-local-login.yml
      - optional:classpath:/local/yml/application-local-redis.yml
      - optional:classpath:/local/yml/application-local-rabbitmq.yml

  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      file: /workspaces/codespaces-blank/docker-compose-local.yml
